In [3]:
# Plotting
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline

# OS
import os

# Math
import numpy as np

# Paths
path = './data/'
pathout = './data/'
pathgraphs = './graphs/'

for p in [path, pathout, pathgraphs]:
    if os.path.exists(p)==False:
        os.mkdir(p)

In [8]:
import pandas as pd

In [4]:
from IPython.display import IFrame
url = 'https://en.wikipedia.org/wiki/List_of_countries_by_population_(United_Nations)'
IFrame(url, width=800, height=400)

In [10]:
popUN_wiki = pd.read_html(url, encoding='utf-8')[0]
popUN_wiki

,Country / Area,UN continentalregion[4],UN statisticalsubregion[4],Population(1 July 2018),Population(1 July 2019),Change
0,China[a],Asia,Eastern Asia,1427647786,1433783686,+0.43%
1,India,Asia,Southern Asia,1352642280,1366417754,+1.02%
2,United States,Americas,Northern America,327096265,329064917,+0.60%
3,Indonesia,Asia,South-eastern Asia,267670543,270625568,+1.10%
4,Pakistan,Asia,Southern Asia,212228286,216565318,+2.04%
...,...,...,...,...,...,...
229,Falkland Islands (United Kingdom),Americas,South America,3234,3377,+4.42%
230,Niue,Oceania,Polynesia,1620,1615,−0.31%
231,Tokelau (New Zealand),Oceania,Polynesia,1319,1340,+1.59%
232,Vatican City[z],Europe,Southern Europe,801,799,−0.25%
233,World,NaN,NaN,7631091040,7713468100,+1.08%